### PR TITLE
[G2M] Create text widget

### LINKED ISSUE #213: Create new Text widget
**Design:**

Screen Shot 2023-01-18 at 1 21 18 PM

### PR DESCRIPTION
**Pull request by geoerika**
Closes #213

**Changes:**

### New Text Widget

- created new basic Text Widget to answer to new design requirements in Figma for auto-insights project
- this is just the initial implementation, more edit controls for customization to be added at a future date

Screen Shot 2023-01-26 at 1 39 51 PM

**Compact Mode:**

Screen Shot 2023-01-26 at 1 41 44 PM

**Create a Text Widget:**

https://user-images.githubusercontent.com/41120953/214922971-b5c173b6-2412-40a4-9443-1b033b4241f6.mov

**Others:**
- refactored state definitions in components that I did changes

### Future Work (hopefully next week)

1. Fix No Data source reset when we try to select a data source in a Text Widget 
2. Add controls for colors & text formatting

### CODE REVIEW

**Review by vlatawiec — APPROVED** [review]
Looks good from the UI side! Thanks for your hard work! :)

**Review by Hamaad102 — APPROVED** [review]
Looks good. Not a major thing but the clear button only clears the widget and not the text box.

Screenshot 2023-01-26 at 2 13 38 PM

**Comment by geoerika** [comment]
> Looks good. Not a major thing but the clear button only clears the widget and not the text box.
> 
> Screenshot 2023-01-26 at 2 13 38 PM

Oh, I was waiting for you to catch on that @Hamaad102 . Unfortunately, I think it is an issue with our lumen-labs component. The TextField.Area comp has this issue only and another one. Try delete all the text in the Value Configuration and see what's happening. It's the same on lumen-labs.

**Comment by kc-leung** [comment]
> > Looks good. Not a major thing but the clear button only clears the widget and not the text box.
> > Screenshot 2023-01-26 at 2 13 38 PM
> 
> Oh, I was waiting for you to catch on that @Hamaad102 . Unfortunately, I think it is an issue with our lumen-labs component. The TextField.Area comp has this issue only and another one. Try delete all the text in the Value Configuration and see what's happening. It's the same in lumen-labs. I will test more later, but that's my initial assessment.

yea it is a lumen-labs problem text area doesn't do the clean up properly it returns [Object Object]

**Review by kc-leung — APPROVED** [review]

**Pull request merged**
