### PR TITLE
[G2M] X Map - add aggregation & controls to hide aggregation label in column name

### PR DESCRIPTION
**Pull request by geoerika**
https://www.notion.so/eqproduct/Add-aggregation-for-cross-visitation-map-in-Widget-Studio-23f921011e3644f59dc6cac90e14b099

**Changes:**

#### X-Map Widget Value Configuration

[Story](https://6139016b390968003a20da5a-yhobbphsdf.chromatic.com/?path=/story/editor-mode--dev-map-3)

- added aggregation controls & used the functions to aggregate data for each of the cross visitation map layers: source, target, arc
- added toggle in Map settings / Display Options to add or remove the agg label in column name in the widget & data
- minor adjustment of spaces around the widget & in Stat widget for better use of space inside the widget for visualizations

Screen Shot 2023-02-08 at 1 34 13 PM

**Recording:**

https://user-images.githubusercontent.com/41120953/217650421-7066a69b-b9aa-43aa-b64d-0353aeda47c7.mov

### CODE REVIEW

**Comment by geoerika** [comment]
**Changes:**

#### X-Map Widget Value Configuration

- added aggregation controls & used the functions to aggregate data for each of the cross visitation map layers: source, target, arc
- added toggle in Map settings / Display Options to add or remove the agg label in column name in the widget & data
- minor adjustment of spaces around the widget & in Stat widget for better use of space inside the widget for visualizations

Screen Shot 2023-02-08 at 1 34 13 PM

**Recording:**

https://user-images.githubusercontent.com/41120953/217650421-7066a69b-b9aa-43aa-b64d-0353aeda47c7.mov

**Review by Hamaad102 — APPROVED** [review]

**Review by woozyking — APPROVED** [review]
Looks good

I would ask @geoerika to put the main description back so we can keep the automated SR&ED digest ([example](https://www.notion.so/eqproduct/MONTH-Digest-Thu-Dec-01-to-Sat-Dec-31-2022-SR-ED-mode-ad7f6fe0b5eb4cdaa48a0c7022e660f1)) working for next year, once @ashishjullia works out the string parsing problem

**Comment by geoerika** [comment]
> Looks good
> 
> I would ask @geoerika to put the main description back so we can keep the automated SR&ED digest ([example](https://www.notion.so/eqproduct/MONTH-Digest-Thu-Dec-01-to-Sat-Dec-31-2022-SR-ED-mode-ad7f6fe0b5eb4cdaa48a0c7022e660f1)) working for next year, once @ashishjullia works out the string parsing problem

Oh yes! I will, once the parsing fix is done.

**Comment by ashishjullia** [comment]
> > Looks good
> > I would ask @geoerika to put the main description back so we can keep the automated SR&ED digest ([example](https://www.notion.so/eqproduct/MONTH-Digest-Thu-Dec-01-to-Sat-Dec-31-2022-SR-ED-mode-ad7f6fe0b5eb4cdaa48a0c7022e660f1)) working for next year, once @ashishjullia works out the string parsing problem
> 
> Oh yes! I will, once the parsing fix is done. Thank you!

[Done](https://github.com/EQWorks/github-app-notion-integration/pull/4), hopefully it won't break in worst case scenarios. :)

**Pull request merged**
